spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/booknest
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: "gotaseptimiuandrei@gmail.com"
    password: "qnhotlsglvgjhfok"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rsa:
  public-key: classpath:certs/public_key.pem
  private-key: classpath:certs/private_key.pem
