spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 8MB

  datasource:
    url: jdbc:mysql://booknest-db.cnsiw6q44cvd.eu-north-1.rds.amazonaws.com:3306/booknest
    username: admin
    password: booknest-db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: "gotaseptimiuandrei@gmail.com"
    password: "qnhotlsglvgjhfok"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rsa:
  public-key: classpath:certs/public_key.pem
  private-key: classpath:certs/private_key.pem

aws:
  s3:
    bucketName: bucket-booknest
    accessKey: AKIARFRKVXID7ZUVVF7Z
    secretKey: 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
    region: eu-north-1

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true


