name: CI - Booknest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-checks:
    name: Frontend Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run lint-staged
        run: npm run lint-staged

      - name: Build frontend
        run: npm run build

  backend-checks:
    name: Backend Format & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Check code formatting
        run: ./mvnw spring-javaformat:validate

      - name: Run backend tests with test profile
        run: ./mvnw test -Dspring.profiles.active=test

  docker-backend:
    name: Dockerize Backend
    runs-on: ubuntu-latest
    needs: backend-checks
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t booknest-backend:latest ./backend
